sonar.projectKey=ISOF-Despliegue_StreamButed
sonar.organization=isof-despliegue

sonar.sources=front-streambuted/src,services/catalog-service/src,services/identity-service/src/main,services/media-service/app,services/streaming-service/app
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/target/**,**/.next/**,**/coverage/**,**/.github/**,**/*.png,**/*.jpg,**/*.jpeg,**/*.gif,**/*.svg,**/*.ico,**/*.webp,**/*.woff,**/*.woff2,**/*.ttf,**/*.eot,docs/**,tests/postman/**,.env.example

sonar.tests=front-streambuted/src,services/catalog-service/tests,services/identity-service/src/test,services/media-service/tests,services/streaming-service/tests
sonar.test.inclusions=front-streambuted/src/**/*.test.*,front-streambuted/src/**/*.spec.*,services/catalog-service/tests/**,services/identity-service/src/test/**,services/media-service/tests/**,services/streaming-service/tests/**

sonar.javascript.lcov.reportPaths=front-streambuted/coverage/lcov.info,services/catalog-service/coverage/lcov.info
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml,**/build/reports/jacoco/test/jacocoTestReport.xml
sonar.python.coverage.reportPaths=services/media-service/coverage.xml,services/streaming-service/coverage.xml

sonar.qualitygate.wait=true
