sonar.projectKey=ISOF-Despliegue_StreamButed
sonar.organization=isof-despliegue

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/target/**,**/.next/**,**/coverage/**,**/.github/**,**/*.png,**/*.jpg,**/*.jpeg,**/*.gif,**/*.svg,**/*.ico,**/*.webp,**/*.woff,**/*.woff2,**/*.ttf,**/*.eot,docs/**,tests/postman/**,.env.example

sonar.tests=.
sonar.test.inclusions=**/*.test.*,**/*.spec.*,**/src/test/**,**/__tests__/**,**/tests/**

sonar.javascript.lcov.reportPaths=front-streambuted/coverage/lcov.info,services/catalog-service/coverage/lcov.info
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml,**/build/reports/jacoco/test/jacocoTestReport.xml
sonar.python.coverage.reportPaths=services/media-service/coverage.xml,services/streaming-service/coverage.xml

sonar.qualitygate.wait=true
